insert into groups(name) values('AA-11');
insert into groups(name) values('BB-12');
insert into groups(name) values('CC-13');
insert into groups(name) values('EE-14');
insert into groups(name) values('FF-15');

insert into students(first_name, last_name, email, phone_number, group_id) values('Ivan','Ivanov','ivan@gmail.com','+78784111225',1);
insert into students(first_name, last_name, email, phone_number, group_id) values('Petr','Petrov','Petr@gmail.com','+78784111221',2);
insert into students(first_name, last_name, email, phone_number, group_id) values('Sidor','Sidorov','Sidor@gmail.com','+78784111222',3);
insert into students(first_name, last_name, email, phone_number, group_id) values('Marina','Marinina','Marina@gmail.com','+78784111223',4);
insert into students(first_name, last_name, email, phone_number, group_id) values('Olga','Oreshkina','Olga@gmail.com','+78784111224',5);
insert into students(first_name, last_name, email, phone_number, group_id) values('Mike','Liebermann','Mike@gmail.com','+78784111226',1);
insert into students(first_name, last_name, email, phone_number, group_id) values('Olaf','Bundesmann','Olaf@gmail.com','+78784111227',2);
insert into students(first_name, last_name, email, phone_number, group_id) values('Brian','May','Brian@gmail.com','+78784111228',3);
insert into students(first_name, last_name, email, phone_number, group_id) values('Taras','Bul`ba','Taras@gmail.com','+78784111229',4);
insert into students(first_name, last_name, email, phone_number, group_id) values('Oleg','Protasov','Oleg@gmail.com','+78784111210',5);
insert into students(first_name, last_name, email, phone_number, group_id) values('Silvio','Berlusconi','Silvio@gmail.com','+78784111211',1);
insert into students(first_name, last_name, email, phone_number, group_id) values('Radgh','Kapur','Radgh@gmail.com','+78784111212',2);
insert into students(first_name, last_name, email, phone_number, group_id) values('Manuella','Rodriges','Manuella@gmail.com','+78784111214',3);
insert into students(first_name, last_name, email, phone_number, group_id) values('Lemmy','Kilmister','Lemmy@gmail.com','+78784111215',4);
insert into students(first_name, last_name, email, phone_number, group_id) values('Ozzy','Osbourne','Ozzy@gmail.com','+78784111216',5);
