CREATE TABLE faculties (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(30) NOT NULL,
    description varchar(250));
    
CREATE TABLE departments (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(30) NOT NULL,
    description varchar(250),
    faculty_id int,
    FOREIGN KEY (faculty_id) REFERENCES faculties (id) on update cascade on delete SET NULL);

CREATE TABLE groups (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    name varchar(30) NOT NULL,
    department_id int,
    FOREIGN KEY (department_id) REFERENCES departments (id) on update cascade on delete SET NULL);
    
CREATE TABLE students (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name varchar(30) NOT NULL,
    last_name varchar(30) NOT NULL,
    group_id int,
    FOREIGN KEY (group_id) REFERENCES groups (id) on update cascade on delete SET NULL);
    
CREATE TABLE subjects (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(30) NOT NULL,
    description varchar(250),
    department_id int NOT NULL,
    FOREIGN KEY (department_id) REFERENCES departments (id) on update cascade on delete SET NULL);
      
CREATE TABLE teachers (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name varchar(30) NOT NULL,
    last_name varchar(30) NOT NULL,
    department_id int,
    subject_id int,
    FOREIGN KEY (department_id) REFERENCES departments (id) on update cascade on delete SET NULL,
    FOREIGN KEY (subject_id) REFERENCES subjects (id) on update cascade on delete SET NULL);

CREATE TABLE auditories (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(30) NOT NULL,
    description varchar(250),
    capacity int DEFAULT NULL);
    
CREATE TABLE lectures (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(30) NOT NULL,
    start_time time NOT NULL,
    end_time time NOT NULL);
    
CREATE TABLE lessons (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id int,
    subject_id int,
    date date NOT NULL,
    auditory_id int NOT NULL,
    lecture_id int NOT NULL,
    FOREIGN KEY (teacher_id) REFERENCES teachers (id) on update cascade on delete SET NULL,
    FOREIGN KEY (subject_id) REFERENCES subjects (id) on update cascade on delete SET NULL,
    FOREIGN KEY (auditory_id) REFERENCES auditories (id) on update cascade,
    FOREIGN KEY (lecture_id) REFERENCES lectures (id) on update cascade);
    
CREATE TABLE lessons_groups (
    group_id int NOT NULL,
    lesson_id int NOT NULL,
    FOREIGN KEY (group_id) REFERENCES groups (id) on delete cascade on update cascade,
    FOREIGN KEY (lesson_id) REFERENCES lessons (id) on delete cascade on update cascade,
    UNIQUE (group_id, lesson_id));
